require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'


pod 'Firebase', :modular_headers => true
pod 'FirebaseCore', :modular_headers => true
pod 'FirebaseCoreInternal', :modular_headers => true
pod 'GoogleUtilities', :modular_headers => true

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end

target 'betfree' do
  config = use_native_modules!
  use_react_native!(:path => config[:reactNativePath],:hermes_enabled => true)

  target 'betfreeTests' do
    inherit! :complete
    # Pods for testing
  end
end

target 'betfree-tvOS' do
  # Pods for betfree-tvOS

  target 'betfree-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
